<template>
  <div class="legal-page">
    <section class="legal-hero">
      <div class="container">
        <span class="section-label">Legal</span>
        <h1 class="section-title">Terms of Use</h1>
        <p class="legal-updated">Last updated: April 10, 2026</p>
      </div>
    </section>

    <section class="legal-content">
      <div class="container">
        <div class="legal-body">

          <div class="legal-block">
            <h2>Agreement</h2>
            <p>By downloading or using Lock It ("the App"), you agree to these terms. If you do not agree, do not use the App. These terms apply to the current version and all future updates unless stated otherwise.</p>
          </div>

          <div class="legal-block">
            <h2>What Lock It is</h2>
            <p>Lock It is a free macOS menu bar application that helps you create focus environments by managing app windows, closing distractions, playing ambient sounds, and tracking focus sessions. The App runs entirely on your computer and does not require an internet connection or user account.</p>
          </div>

          <div class="legal-block">
            <h2>License</h2>
            <p>Lock It is provided as free software for personal use. You may install it on any number of Macs you own. You may not reverse-engineer, decompile, modify, or redistribute the App or any of its components without prior written permission.</p>
          </div>

          <div class="legal-block">
            <h2>System permissions</h2>
            <p>Lock It requires macOS Accessibility permission to function. This permission allows the App to open and arrange application windows, activate grayscale mode, and manage running processes during a focus session. Granting this permission is voluntary — the App will prompt you on first use and you can revoke it at any time in System Settings.</p>
          </div>

          <div class="legal-block">
            <h2>Your data</h2>
            <p>All data generated by Lock It — including focus profiles, session history, and statistics — is stored locally on your computer. The App does not transmit any data to external servers. You retain full ownership and control over your data. For details, see our <NuxtLink to="/privacy">Privacy Policy</NuxtLink>.</p>
          </div>

          <div class="legal-block">
            <h2>Disclaimer of warranties</h2>
            <p>Lock It is provided "as is" without warranty of any kind, express or implied, including but not limited to warranties of merchantability, fitness for a particular purpose, or non-infringement. The App interacts with macOS system features — behavior may vary across macOS versions and hardware configurations.</p>
          </div>

          <div class="legal-block">
            <h2>Limitation of liability</h2>
            <p>In no event shall the developer of Lock It be liable for any indirect, incidental, special, or consequential damages arising from the use or inability to use the App, including but not limited to loss of data, interruption of workflow, or system incompatibility.</p>
          </div>

          <div class="legal-block">
            <h2>App closing behavior</h2>
            <p>When a focus session starts, Lock It may close applications that are not part of the active profile. By using this feature, you accept responsibility for saving your work in other applications before starting a session. The App provides confirmation before activating a session.</p>
          </div>

          <div class="legal-block">
            <h2>Updates</h2>
            <p>Lock It does not auto-update. New versions are published on the official website and GitHub. You are free to update at your own pace. Continuing to use the App after an update constitutes acceptance of any revised terms.</p>
          </div>

          <div class="legal-block">
            <h2>Changes to these terms</h2>
            <p>These terms may be updated from time to time. Changes will be posted on this page with an updated date. Your continued use of the App after changes are posted constitutes acceptance of the revised terms.</p>
          </div>

          <div class="legal-block">
            <h2>Contact</h2>
            <p>Questions about these terms? Reach out at <a href="mailto:support@lockit.app">support@lockit.app</a>.</p>
          </div>

        </div>
      </div>
    </section>
  </div>
</template>

<script setup>
useHead({
  title: 'Terms of Use — Lock It',
  meta: [
    { name: 'description', content: 'Lock It terms of use. Free macOS app, no accounts, no data collection. Simple terms for a simple app.' },
    { property: 'og:title', content: 'Terms of Use — Lock It' },
    { property: 'og:description', content: 'Terms of use for Lock It — the free focus app for macOS.' },
  ]
})
</script>

<style scoped>
.legal-page { padding-top: 100px; }

.legal-hero { padding: 60px 0 40px; text-align: center; }

.legal-updated {
  font-size: 13px; color: var(--text-muted); margin-top: 8px;
}

.legal-content { padding: 40px 0 120px; }

.legal-body { max-width: 680px; margin: 0 auto; }

.legal-block { margin-bottom: 40px; }
.legal-block:last-child { margin-bottom: 0; }

.legal-block h2 {
  font-size: 17px; font-weight: 700; color: var(--text-primary);
  margin-bottom: 12px; letter-spacing: -0.2px;
}

.legal-block p {
  font-size: 14px; color: var(--text-secondary); line-height: 1.75;
}

.legal-block p a,
.legal-block p :deep(a) {
  color: var(--text-primary); text-decoration: underline;
  text-underline-offset: 3px; text-decoration-color: var(--border-light);
  transition: var(--transition);
}
.legal-block p a:hover,
.legal-block p :deep(a):hover { text-decoration-color: var(--text-primary); }

@media (max-width: 640px) {
  .legal-hero { padding: 40px 0 24px; }
  .legal-content { padding: 24px 0 80px; }
}
</style>
